HostelApp/Models/Room.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HostelApp.Models
{
    public class Room
    {
        public int ID { get; set; }

        [Required]
        public int RoomNumber { get; set; }

        public bool IsReserved { get; set; }

        [Required]
        public int BedCount { get; set; }

        public bool WiFi { get; set; }

        public bool Breakfast { get; set; }

        public string Description { get; set; }

        [Required]
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }

        [Required]
        public decimal Price { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<RoomImage> RoomImages { get; set; }
    }
}

HostelApp/Areas/HostelAdmin/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HostelApp.DAL;
using HostelApp.Models;
using HostelApp.Areas.HostelAdmin.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HostelApp.Areas.HostelAdmin.Controllers
{
    [Area("HostelAdmin")]
    public class RoomController : Controller
    {
        private readonly AppDbContext _dbContext;
        private readonly IHostingEnvironment _env;

        public RoomController(AppDbContext dbContext, IHostingEnvironment env)
        {
            _dbContext = dbContext;
            _env = env;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Room> rooms = await _dbContext.Rooms.Include(x => x.Category).Include(x => x.RoomImages).ToListAsync();
            return View(rooms);
        }

        public async Task<IActionResult> Create()
        {
            RoomVM roomVM = new RoomVM
            {
                Categories = await _dbContext.Categories.ToListAsync()
            };

            return View(roomVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoomVM roomVM)
        {
           
            if (!ModelState.IsValid)
            {
                roomVM.Categories = await _dbContext.Categories.ToListAsync();
                return View(roomVM.Categories);
            }

            Room room = new Room
            {
                RoomNumber = roomVM.Room.RoomNumber,
                CategoryId = roomVM.SelectedCategory,
                BedCount = roomVM.Room.BedCount,
                Breakfast = roomVM.Room.Breakfast,
                Description = roomVM.Room.Description,
                IsReserved = roomVM.Room.IsReserved,
                Price = roomVM.Room.Price,
                WiFi = roomVM.Room.WiFi
            };

            await _dbContext.AddAsync(room);

            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            Room room = await _dbContext.Rooms.Where(x => x.ID == id).Include(x => x.Category).Include(x => x.RoomImages).FirstOrDefaultAsync();
            if (room == null)
                return NotFound();

            return View(room);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            RoomVM roomVM = new RoomVM
            {
                Room = await _dbContext.Rooms.Where(x => x.ID == id).Include(x => x.Category).Include(x => x.RoomImages).FirstOrDefaultAsync(),
                Categories = await _dbContext.Categories.ToListAsync()
            };

            if (roomVM == null)
                return NotFound();

            return View(roomVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, RoomVM roomVM)
        {
            IEnumerable<Category> categories = await _dbContext.Categories.ToListAsync();

            if (id == null)
            {
                roomVM.Categories = categories;
            }

            if (!ModelState.IsValid)
            {
                roomVM.Categories = categories;
            }

            Room room = await _dbContext.Rooms.FindAsync(id);

            room.RoomNumber = roomVM.Room.RoomNumber;
            room.Price = roomVM.Room.Price;
            room.IsReserved = roomVM.Room.IsReserved;
            room.CategoryId = roomVM.SelectedCategory;
            room.Description = roomVM.Room.Description;
            room.Breakfast = roomVM.Room.Breakfast;
            room.WiFi = roomVM.Room.WiFi;
            room.BedCount = roomVM.Room.BedCount;

            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            Room room = await _dbContext.Rooms.FindAsync(id);
            if (room == null)
                return NotFound();

            _dbContext.Rooms.Remove(room);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

HostelApp/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using HostelApp.DAL;
using HostelApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HostelApp.Controllers
{
    public class OrdersController : Controller
    {
        private readonly AppDbContext _dbContext;
        private readonly UserManager<AppUser> _userManager;
        public OrdersController(AppDbContext dbContext, UserManager<AppUser> userManager)
        {
            _dbContext = dbContext;
            _userManager = userManager;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(string startDate, string endDate, int? count, int? roomId)
        {
            if (startDate == null || endDate == null || count == null || roomId == null)
            {
                return RedirectToAction("Error", "Home");
            }
           
           
            Room room = await _dbContext.Rooms.FindAsync(roomId);

            var user = await _dbContext.Users.SingleOrDefaultAsync(x => _userManager.FindByNameAsync(User.Identity.Name).GetAwaiter().GetResult().Id == x.Id);

            if (user == null)
            {
                return RedirectToAction("Login", "Account");
            }

            Order order = new Order
            {
                RoomId = Convert.ToInt32(roomId),
                AppUserId = user.Id,
                StartDate = DateTime.ParseExact(startDate, "M/d/yyyy", CultureInfo.InvariantCulture),
                EndDate = DateTime.ParseExact(endDate, "M/d/yyyy", CultureInfo.InvariantCulture),
                IsReserved = true,
                FreeBedCount = 0
            };

            await _dbContext.Orders.AddAsync(order);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

HostelApp/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HostelApp.DAL;
using HostelApp.Models;
using HostelApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HostelApp.Controllers
{
    public class RoomController : Controller
    {
        private readonly AppDbContext _dbContext;
        public RoomController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }


        public async Task<IActionResult> Index(DateTime? startDate, DateTime? endDate, int? count)
        {
            if (startDate == null || endDate == null || count == null)
            {
                return RedirectToAction("Error", "Home");
            }

            RoomVM roomVM = new RoomVM();

            string selectedDates = "";

            for (DateTime day = Convert.ToDateTime(startDate); day <= endDate; day = day.AddDays(1))
            {
                selectedDates += "<" + day.ToShortDateString() + ">";
            }

            string orderId = "";
            IEnumerable<Order> orders = await _dbContext.Orders.ToListAsync();

            foreach (var order in orders)
            {
                for (DateTime orderDay = order.StartDate.Date; orderDay <= order.EndDate.Date; orderDay = orderDay.AddDays(1))
                {
                    if (selectedDates.Contains("<" + orderDay.ToShortDateString() + ">"))
                    {
                        orderId += "/" + order.ID + "/";
                    }
                }
            }

            IEnumerable<Room> rooms = from room in _dbContext.Rooms
                                      join category in _dbContext.Categories
                                      on room.CategoryId equals category.Id
                                      join order in _dbContext.Orders
                                      on room.ID equals order.RoomId
                                      join roomImage in _dbContext.RoomImages
                                      on room.ID equals roomImage.RoomId
                                      where (orderId.Contains("/" + order.ID.ToString() + "/"))
                                      select new Room
                                      {
                                          ID = room.ID
                                      };

            string roomId = "";

            foreach (var room in rooms)
            {
                roomId += "/" + room.ID + "/";
            }

            roomVM.Rooms = await _dbContext.Rooms
                .Include(x => x.RoomImages)
                    .Include(x => x.Category)
                        .Where(x => !roomId.Contains("/" + x.ID.ToString() + "/")).ToListAsync();

            return View(roomVM);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            Room room = await _dbContext.Rooms.Where(x => x.ID == id).Include(x => x.Category).Include(x => x.RoomImages).FirstOrDefaultAsync();
            if (room == null)
                return RedirectToAction("Error", "Home");

            return View(room);
        }

        public async Task<IActionResult> AllRooms()
        {
            IEnumerable<Room> Rooms = await _dbContext.Rooms
                                                        .Include(x=>x.RoomImages)
                                                            .Include(x=>x.Category).ToListAsync();
            return View(Rooms);
        }
    }
}

HostelApp/Views/Room/AllRooms.cshtml
@model IEnumerable<Room>
@{
    ViewData["Title"] = "AllRooms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="mg-best-rooms pt-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="mg-sec-title undefined">
                    <h2>All Rooms</h2>
                    <p>These best rooms chosen by our customers</p>
                </div>
                <div class="row">
                    @foreach (var room in Model)
                    {
                        <div class="col-md-4">
                            <figure class="mg-room">
                                @for (int i = 0; i < room.RoomImages.Count(); i++)
                                {
                                    <img style="height: 208px;@(i==0? "display:block;" : "display:none;")" class="img-fluid" src="~/images/room/@room.RoomImages.ElementAt(i).Image" alt="img11" />
                                }
                                <figcaption>
                                    <h2>@room.Category.CategoryName</h2>
                                    <div class="mg-room-rating">
                                        <i class="fa fa-star"> </i> 5.0
                                    </div>
                                    <div class="mg-room-price">@room.Price<sup>/Month</sup></div>
                                    <p>@room.Description</p><a class="btn btn-link" asp-action="Details" asp-controller="Room" asp-route-id="@room.ID">View Details<i class="fa fa-angle-double-right"></i></a>
                                </figcaption>
                            </figure>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

HostelApp/Views/Room/Details.cshtml
@model Room
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/hosteladmin/css/bootstrap.css" rel="stylesheet" />
<link href="~/hosteladmin/css/main.css" rel="stylesheet" />


<div class="" style="height:700px; padding:150px 0 200px 0; ">
    <div class="col-md-4" style="padding-bottom:50px;">
        <div class="form-group">
            <div class="col-md-6">
                <label class="control-label">Room Number:</label>
            </div>
            <input type="hidden" id="roomId" value="@Model.ID" />
            <div class="col-md-6" style="text-align:center;">
                <label class="control-label" style="color:#7E7E7E;">@Model.RoomNumber</label>
            </div>
        </div>
        <div class="form-group" style="padding-top:30px;">
            <div class="col-md-6">
                <label class="control-label">Category:</label>
            </div>
            <div class="col-md-6" style="text-align:center;">
                <label class="control-label" style="color:#7E7E7E;">@Model.Category.CategoryName</label>
            </div>
        </div>
        <div class="form-group" style="padding-top:30px;">
            <div class="col-md-6">
                <label class="control-label">Bed Count:</label>
            </div>
            <div class="col-md-6" style="text-align:center;">
                <label class="control-label bed-count" style="color:#7E7E7E;">@Model.BedCount</label>
            </div>
        </div>
        <div class="form-group" style="padding-top:30px;">
            <div class="col-md-6">
                <label class="control-label">Breakfast:</label>
            </div>
            <div class="col-md-6" style="text-align:center;">
                <label class="control-label" style="color:#7E7E7E;">@Model.Breakfast</label>
            </div>
        </div>
        <div class="form-group" style="padding-top:30px;">
            <div class="col-md-6">
                <label class="control-label">WI-FI:</label>
            </div>
            <div class="col-md-6" style="text-align:center;">
                <label class="control-label" style="color:#7E7E7E;">@Model.WiFi</label>
            </div>
        </div>
        <div class="form-group room-order" style="padding-top:30px;">
            <div class="col-md-6">
                <label class="control-label">Price:</label>
            </div>
            <div class="col-md-6" style="text-align:center;">
                <label class="control-label price" style="color:#7E7E7E;">@Model.Price</label>
            </div>
            <div class="col-md-6">
                <label class="control-label">Resreved:</label>
            </div>
            <div class="col-md-6" style="text-align:center;">
                @{
                    bool isReserved = Model.IsReserved;
                }
                @if (isReserved == true)
                {
                    <label class="control-label" style="color:#7E7E7E;">Yes</label>
                }
                @if (isReserved == false)
                {
                    <label class="control-label" style="color:#7E7E7E;">No</label>
                }
            </div>
        </div>
        <div class="form-group" style="padding-top:30px;">
            <div class="col-md-6">
                <label class="control-label">Description:</label>
            </div>
            <div class="col-md-6" style="text-align:center;">
                <label class="control-label" style="color:#7E7E7E;">@Model.Description  </label>
            </div>
        </div>
    </div>
    <div class="col-md-8" style="padding-bottom:50px;">
        <div id="slider">
            <div class="images">
                @for (int i = 0; i < Model.RoomImages.Count(); i++)
                {
                    <div class="item @(i == 0 ? "active" : "")">
                        <img src="~/images/room/@Model.RoomImages.ElementAt(i).Image" alt="slider image ">
                    </div>
                }
            </div>
            <div class="icon left" id="left">
                <i class="fas fa-chevron-left"></i>
            </div>

            <div class="icon right" id="right">
                <i class="fas fa-chevron-right"></i>
            </div>
        </div>
    </div>
    <form asp-action="Index" asp-controller="Orders" method="post" class="container-fluid">
        <div class="row">
            <input type="hidden" name="roomId" value="@Model.ID" />
            <div class="col-md-6 col-lg-3">
                <div class="input-group date mg-check-in">
                    <div class="input-group-addon"><i class="far fa-calendar-alt"></i></div>
                    <input name="startDate" class="form-control checkIn" type="text" id="exampleInputEmail1" placeholder="Check In" autocomplete="off">
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="input-group date mg-check-out">
                    <div class="input-group-addon"><i class="far fa-calendar-alt"></i></div>
                    <input name="endDate" class="form-control checkOut" type="text" id="exampleInputEmail1" placeholder="Check Out" autocomplete="off">
                </div>
            </div>
            <div class="col-md-12 col-lg-3">
                <div class="row">
                    <div class="col-6">
                        <select name="count" style="padding:0 0 0 10px; height:32px;" class="form-control" id="count">
                            <option value="">Count</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                        </select>
                    </div>

                </div>
            </div>
            <div class="col-md-12 col-lg-3">
                <input type="submit" class="btn btn-main btn-block" value="Order" id="check">
            </div>
        </div>
    </form>
</div>
<script src="~/js/jquery.min.js"></script>
<script src="~/hosteladmin/js/main.js"></script>
<script src="~/js/main.js"></script>

HostelApp/Views/Room/Index.cshtml
@model RoomVM
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="mg-best-rooms">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="mg-sec-title undefined">
                    <h2>Our Rooms</h2>
                    <p>These best rooms chosen by our customers</p>
                </div>
                <div class="row">
                    @foreach (var room in Model.Rooms)
                    {
                        <div class="col-md-4">
                            <figure class="mg-room ">
                                @for (int i = 0; i < room.RoomImages.Count(); i++)
                                {
                                    <img style="height: 208px;@(i==0? "display:block;" : "display:none;")" class="img-fluid" src="~/images/room/@room.RoomImages.ElementAt(i).Image" alt="img11" />
                                }
                                <figcaption>
                                    <h2>@room.Category.CategoryName</h2>
                                    <div class="mg-room-rating">
                                        <i class="fa fa-star"> </i> 5.0
                                    </div>
                                    <div class="mg-room-price">@room.Price<sup>/Month</sup></div>
                                    <p>@room.Description</p><a class="btn btn-link" asp-action="Details" asp-controller="Room" asp-route-id="@room.ID">View Details<i class="fa fa-angle-double-right"></i></a>
                                </figcaption>
                            </figure>
                        </div>

                    }
                </div>
                <div class="text-center">
                    <a asp-action="Index" asp-controller="Room" class="btn btn-primary">All rooms</a>
                </div>
            </div>
        </div>
    </div>
</section>