HostelApp/Models/Slider.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HostelApp.Models
{
    public class Slider
    {
        public int ID { get; set; }

        [StringLength(200)]
        public string Image { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [Required]
        [StringLength(255)]
        public string Content { get; set; }

        [NotMapped]
        public IFormFile Photo { get; set; }
    }
}

HostelApp/Areas/HostelAdmin/Controllers/SlidersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using HostelApp.DAL;
using HostelApp.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using static HostelApp.Extensions.IFormFileExtension;

namespace HostelApp.Areas.HostelAdmin.Controllers
{
    [Area("HostelAdmin")]
    public class SlidersController : Controller
    {
        private readonly AppDbContext _dbContext;
        private readonly IHostingEnvironment _env;
        public SlidersController(AppDbContext dbContext, IHostingEnvironment env)
        {
            _dbContext = dbContext;
            _env = env;
        }

        public IActionResult Index()
        {
            List<Slider> sliders = _dbContext.Sliders.ToList();
            return View(sliders);
        }

        public IActionResult Create()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Create(Slider slider)
        {
            if (ModelState["Photo"].ValidationState == ModelValidationState.Invalid)
            {
                return View();
            }

            if (!slider.Photo.IsImage())
            {
                ModelState.AddModelError("Photo", "File type is not valid!!!");
                return View();
            }

            string fileName = await slider.Photo.SaveAsync(_env.WebRootPath, "images", "slider");
            slider.Image = fileName;

            await _dbContext.Sliders.AddAsync(slider);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
                return NotFound();

            Slider slider = _dbContext.Sliders.Find(id);

            if (slider == null)
                return NotFound();

            return View(slider);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, Slider slider)
        {
            if (!ModelState.IsValid)
            {
                return View(slider);
            }

            if (id == null)
            {
                return NotFound();
            }

            Slider sliderFromDb = await _dbContext.Sliders.FindAsync(id);

            if (slider.Photo != null)
            {
                if (!slider.Photo.ContentType.Contains("image/"))
                {
                    ModelState.AddModelError("Photo", "File type is not valid!!!");
                    return View(slider);
                }

                RemoveFile(_env.WebRootPath, "images", "slider", sliderFromDb.Image);

                string fileName = await slider.Photo.SaveAsync(_env.WebRootPath, "images", "slider");
                sliderFromDb.Image = fileName;
            }
            sliderFromDb.Title = slider.Title;
            sliderFromDb.Content = slider.Content;
            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();

            Slider slider = _dbContext.Sliders.Find(id);

            if (slider == null)
                return NotFound();

            return View(slider);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int? id)
        {
            if (id == null)
                return NotFound();
            Slider slider = await _dbContext.Sliders.FindAsync(id);

            if (slider == null)
                return NotFound();


            RemoveFile(_env.WebRootPath, "images", "slider", slider.Image);

            _dbContext.Sliders.Remove(slider);
            _dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

HostelApp/Areas/HostelAdmin/Views/Sliders/Create.cshtml
@model Slider
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/HostelAdmin/Views/Shared/_AdminLayout.cshtml";
}

    <form asp-area="HostelAdmin" asp-controller="Sliders" asp-action="Create" method="post" enctype="multipart/form-data">
        <div class="form-group col-lg-4">
            <div id="imgPreview">
                <img src="" style=" border:1px solid black; height:200px; width:100%;" id="image">
            </div>
            <input style="margin-top:5px" ; accept="image/*" asp-for="Photo" type="file" onchange="showImage.call(this)" />
            <span class="text-danger red" asp-validation-for="Photo"></span>
        </div>
        <div class="col-lg-8">
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input type="text" asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content"></label>
                <input type="text" asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <input type="submit" class="btn btn-success btn-block btn-lg" value="Create" />
        </div>
    </form>
    <div class="col-lg-12">
        <a asp-action="Index" class="btn btn-primary btn-block btn-lg" style="margin:30px 0">
            <i class="fas fa-long-arrow-alt-left"></i>Back to Index
        </a>
    </div>

HostelApp/Areas/HostelAdmin/Views/Sliders/Delete.cshtml
@model Slider
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/HostelAdmin/Views/Shared/_AdminLayout.cshtml";
}

<div class="form-group col-lg-4">
    <div id="imgPreview">
        <img src="~/images/slider/@Model.Image" style=" border:1px solid black; height:200px; width:100%;" id="image">
    </div>
</div>
<div class="col-lg-8">
    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input type="text" asp-for="Title" disabled class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Content"></label>
        <input type="text" asp-for="Content" disabled class="form-control" />
    </div>
    <form method="post" asp-area="HostelAdmin" asp-action="Delete" asp-controller="Sliders">
        <div class="alert alert-danger">
            <p style="padding-top:0;">Are you sure delete this slider?</p>
        </div>
        <input type="submit" class="btn btn-danger btn-block btn-lg" value="Delete" />
    </form>
</div>
<div class="col-lg-12">
    <a asp-action="Index" class="btn btn-primary btn-block btn-lg" style="margin:30px 0">
        <i class="fas fa-long-arrow-alt-left"></i>Back to Index
    </a>
</div>

HostelApp/Areas/HostelAdmin/Views/Sliders/Edit.cshtml
@model Slider
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/HostelAdmin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-area="HostelAdmin" asp-controller="Sliders" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div class="form-group col-lg-4">
        <div id="imgPreview">
            <img src="~/images/slider/@Model.Image" style=" border:1px solid black; height:200px; width:100%;" id="image">
        </div>
        <input style="margin-top:5px"; accept="image/*" asp-for="Photo" type="file" onchange="showImage.call(this)" />
        <span class="text-danger red" asp-validation-for="Photo"></span>
    </div>
    <div class="col-lg-8">
        <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input type="text" asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Content"></label>
            <input type="text" asp-for="Content" class="form-control" />
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <input type="submit" class="btn btn-success btn-block btn-lg" value="Edit" />
    </div>
</form>
<div class="col-lg-12">
    <a asp-action="Index" class="btn btn-primary btn-block btn-lg" style="margin:30px 0">
        <i class="fas fa-long-arrow-alt-left"></i>Back to Index
    </a>
</div>

HostelApp/Areas/HostelAdmin/Views/Sliders/Index.cshtml
@model IEnumerable<Slider>
@{
    ViewBag.Title = "Sliders";
    Layout = "~/Areas/HostelAdmin/Views/Shared/_AdminLayout.cshtml";
}
<div class="row my-3">
    <div class="col-12">
        <a asp-area="HostelAdmin" asp-controller="Sliders" asp-action="Create" class="btn btn-primary btn-block">
            <i class="fas fa-plus"></i> Create New Slider
        </a>
    </div>
</div>
<table class="table table-bordered table-hover table-responsive pt-3">
    <thead>
        <tr>
            <th>Image</th>
            <th>Title</th>
            <th>Content</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var slider in Model)
        {
            <tr>
                <td><img style="width:150px;" src="~/images/slider/@slider.Image" class="img-thumbnail" /></td>
                <td style="vertical-align:middle; text-align:center;">@slider.Title</td>
                <td style="vertical-align:middle; text-align:center;">@slider.Content</td>
                <td style="vertical-align:middle; text-align:center;">
                    @if (Model.Count() > 1)
                    {
                        <a asp-area="HostelAdmin" asp-controller="Sliders" asp-action="Edit" asp-route-id="@slider.ID" class="btn btn-warning"><i class="fas fa-pen"></i></a>
                        <a asp-area="HostelAdmin" asp-controller="Sliders" asp-action="Delete" asp-route-id="@slider.ID" class="btn btn-danger"><i class="far fa-trash-alt"></i></a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>