HostelApp/Models/RoomImage.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HostelApp.Models
{
    public class RoomImage
    {
        public int ID { get; set; }

        [Required]
        public int RoomId { get; set; }
        public virtual Room Room { get; set; }

        public string Image { get; set; }

        [NotMapped]
        public IFormFile Photo { get; set; }
    }
}

HostelApp/Areas/HostelAdmin/Controllers/RoomImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HostelApp.DAL;
using HostelApp.Extensions;
using HostelApp.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using static HostelApp.Extensions.IFormFileExtension;

namespace HostelApp.Areas.HostelAdmin.Controllers
{
    [Area("HostelAdmin")]
    public class RoomImagesController : Controller
    {
        private readonly AppDbContext _dbContext;
        private readonly IHostingEnvironment _env;

        public RoomImagesController(AppDbContext dbContext, IHostingEnvironment env)
        {
            _dbContext = dbContext;
            _env = env;
        }


        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
                return NotFound();

            IEnumerable<RoomImage> roomImages = await _dbContext.RoomImages.Include(x => x.Room).Where(x => x.Room.ID == id).ToListAsync();

            if (roomImages == null)
                return NotFound();
            ViewBag.RoomId = id;

            return View(roomImages);
        }

        public IActionResult Create(int? id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, RoomImage roomImages)
        {
            if (id == null)
                return NotFound();
            if (ModelState["Photo"].ValidationState == ModelValidationState.Invalid)
            {
                return View();
            }

            if (!roomImages.Photo.IsImage())
            {
                ModelState.AddModelError("Photo", "File type is not valid!!!");
                return View();
            }

            string fileName = await roomImages.Photo.SaveAsync(_env.WebRootPath, "images", "room");


            RoomImage images = new RoomImage
            {
                RoomId = id,
                Image = fileName
            };

            await _dbContext.RoomImages.AddAsync(images);
            await _dbContext.SaveChangesAsync();


            return Redirect("/HostelAdmin/RoomImages/Index/" + id.ToString());
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            RoomImage roomImages = await _dbContext.RoomImages.FindAsync(id);

            if (roomImages == null)
                return NotFound();

            return View(roomImages);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, RoomImage roomImages)
        {
            if (!ModelState.IsValid)
            {
                return View(roomImages);
            }

            if (id == null)
            {
                return NotFound();
            }

            RoomImage roomImagesFromDb = await _dbContext.RoomImages.Where(x => x.ID == id).Include(x => x.Room).FirstOrDefaultAsync();

            int roomId = roomImagesFromDb.Room.ID;

            if (roomImages.Photo != null)
            {
                if (!roomImages.Photo.ContentType.Contains("image/"))
                {
                    ModelState.AddModelError("Photo", "File type is not valid!!!");
                    return View(roomImages);
                }

                RemoveFile(_env.WebRootPath, "images", "room", roomImagesFromDb.Image);

                string fileName = await roomImages.Photo.SaveAsync(_env.WebRootPath, "images", "room");
                roomImagesFromDb.Image = fileName;
            }

            await _dbContext.SaveChangesAsync();
            return Redirect("/HostelAdmin/RoomImages/Index/" + roomId.ToString());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {

            if (id == null)
                return NotFound();
            RoomImage roomImages = await _dbContext.RoomImages.Where(x=>x.ID==id).Include(x=>x.Room).FirstOrDefaultAsync();

            if (roomImages == null)
                return NotFound();

            int roomId = roomImages.Room.ID;

            RemoveFile(_env.WebRootPath, "images", "room", roomImages.Image);

            _dbContext.RoomImages.Remove(roomImages);
            _dbContext.SaveChanges();

            return Redirect("/HostelAdmin/RoomImages/Index/" + roomId.ToString());

        }
    }
}

HostelApp/Areas/HostelAdmin/Views/RoomImages/Create.cshtml
@model RoomImage
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/HostelAdmin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-area="HostelAdmin" asp-controller="RoomImages" asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="form-group col-lg-8">
        <div id="imgPreview">
            <img src="" style=" border:1px solid black; height:400px; width:100%;" id="image">
        </div>
        <input style="margin-top:5px" ; accept="image/*" asp-for="Photo" type="file" onchange="showImage.call(this)" />
        <span class="text-danger red" asp-validation-for="Photo"></span>
    </div>
    <div class="col-lg-8">
        <input type="submit" class="btn btn-success btn-block btn-lg" value="Create" />
    </div>
</form>
<div class="col-lg-12">
    <a asp-action="Index" class="btn btn-primary btn-block btn-lg" style="margin:30px 0">
        <i class="fas fa-long-arrow-alt-left"></i>Back to Index
    </a>
</div>

HostelApp/Areas/HostelAdmin/Views/RoomImages/Edit.cshtml
@model RoomImage
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/HostelAdmin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-area="HostelAdmin" asp-controller="RoomImages" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <div id="imgPreview">
            <img src="~/images/room/@Model.Image" style=" border:1px solid black; height:500px; width:100%;" id="image">
        </div>
        <input style="margin-top:5px" ; accept="image/*" asp-for="Photo" type="file" onchange="showImage.call(this)" />
        <span class="text-danger red" asp-validation-for="Photo"></span>
    </div>
    <div class="col-lg-8">
        <input type="submit" class="btn btn-success btn-block btn-lg" value="Edit" />
    </div>
</form>
<div class="col-lg-12">
    <a asp-action="Index" class="btn btn-primary btn-block btn-lg" style="margin:30px 0">
        <i class="fas fa-long-arrow-alt-left"></i>Back to Index
    </a>
</div>

HostelApp/Areas/HostelAdmin/Views/RoomImages/Index.cshtml
@model IEnumerable<RoomImage>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/HostelAdmin/Views/Shared/_AdminLayout.cshtml";
}
@{
    int roomId = 0;
    for(int i=0; i<Model.Count(); i++)
    {
        roomId = Model.ElementAt(0).Room.ID;
    }
}

<div class="row my-3">
    <div class="col-12">
        <a asp-area="HostelAdmin" asp-controller="RoomImages" asp-action="Create" asp-route-id="@ViewBag.RoomId" class="btn btn-primary btn-block">
            <i class="fas fa-plus"></i> Add New Image
        </a>
    </div>
</div>
<table class="table table-bordered table-hover table-responsive pt-3">
    <thead>
        <tr>
            <th>Image</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var roomImage in Model)
        {
            <tr>
                <td><img style="width:150px;" src="~/images/room/@roomImage.Image" class="img-thumbnail" /></td>
                <td style="vertical-align:middle; text-align:center;">
                    @if (Model.Count() > 1)
                    {
                        <a asp-area="HostelAdmin" asp-controller="RoomImages" asp-action="Edit" asp-route-id="@roomImage.ID" class="btn btn-warning"><i class="fas fa-pen"></i></a>
                        <form style="display:inline;" asp-area="HostelAdmin" asp-controller="RoomImages" asp-action="Delete" asp-route-id="@roomImage.ID" method="post">
                            <input type="hidden" name="id" value="@roomImage.ID"/>
                            <button type="submit" class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
                        </form>
                       
                    }
                </td>
            </tr>
        }
    </tbody>
</table>